### ISSUE TITLE
Icons duplicate when running some applications 

### ISSUE THREAD

**Issue by fvroig** [Cairo-Dock/cairo-dock-core#25]
I installed Cairo Dock 3.4.1 in Ubuntu Budgie 24.04 using the distro repository. 

I did not installed all the plugins, but only: `dbus`, `desklet-rendering`, `dialog-rendering`, `gmenu`, `gnome-integration`, `plug-in-data`, and `rendering`.

The dock works very well, but it shows this strange beahvior: for some applications, the icon is duplicated when the application is launched, as in the case of Chrome and Firefox shown in this snapshot:

![Snapshot_2024-08-02_13-00-43](https://github.com/user-attachments/assets/aa063e8b-a9be-4fdc-afdc-b2a64c0fc986)

Note that when I close Firefox, the duplicated icon disappears:

![Snapshot_2024-08-02_12-59-29](https://github.com/user-attachments/assets/f9749476-7513-4eee-af5d-ef75cd795ec8)

But for the other applications, the icon is not duplicated when the application is launched, as in the case of Thunderbird, WhatsApp, and Files in this snapshot:

![Snapshot_2024-08-02_13-01-54](https://github.com/user-attachments/assets/8b26825b-7eed-4b80-b3ad-b9ef6c7209c8)

Curiously, of all the applications I tested, this behavior of duplicated icons only happens with the two web browsers.

Is there any reason for this? Is it a bug or an expected behavior? Why?

**Comment by dkondor** [comment]
Hi,

unfortunately, identifying apps has a lot of corner cases. The workaround is:
1. right click the launcher, point to its name and select "edit" in the submenu
2. Open the "Extra parameters" subgroup
3. In the line "Class of the program", click on "grab" and then click on an open window of the app
4. The detected name / class should appear
5. Click apply, and this should hopefully fix things for this app

You could also try installing the dev version from here: https://launchpad.net/~cairo-dock-team/+archive/ubuntu/weekly
This includes several improvement to identifying apps -- it would be very helpful if you could test if it works in your case :)

**Comment by dkondor** [comment]
![20240803_16h06m27s_grim](https://github.com/user-attachments/assets/6c60a913-8bb5-4593-a207-d5d38a2151a3)

**Comment by fvroig** [comment]
Thanks @dkondor
The grab sequence fix it!
