### ISSUE TITLE
Compilation of beta4 fails on Manjaro KDE6 (cairo_dock_change_nb_viewports)

### ISSUE THREAD

**Issue by Raphisu** [Cairo-Dock/cairo-dock-core#53]
Hi,
compilation of latest update (beta4) fails to compile on Manjaro KDE6.

`[ 30%] Building C object src/implementations/CMakeFiles/implementations.dir/cairo-dock-foreign-toplevel.c.o
/var/tmp/pamac-build-raphael/cairo-dock-core-wayland-git/src/cairo-dock-core-wayland-git/src/implementations/cairo-dock-compiz-integration.c: In Funktion »_add_workspace«:
/var/tmp/pamac-build-raphael/cairo-dock-core-wayland-git/src/cairo-dock-core-wayland-git/src/implementations/cairo-dock-compiz-integration.c:342:44: Fehler: Übergabe des Arguments 2 von »cairo_dock_change_nb_viewports« von inkompatiblem Zeigertyp [-Wincompatible-pointer-types]
  342 |         cairo_dock_change_nb_viewports (1, _compiz_set_nb_viewports);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            gboolean (*)(int,  int) {alias int (*)(int,  int)}
In Datei, eingebunden von /var/tmp/pamac-build-raphael/cairo-dock-core-wayland-git/src/cairo-dock-core-wayland-git/src/implementations/cairo-dock-compiz-integration.c:34:
/var/tmp/pamac-build-raphael/cairo-dock-core-wayland-git/src/cairo-dock-core-wayland-git/src/implementations/cairo-dock-X-utilities.h:81:83: Anmerkung: »GldiChangeViewportFunc« {alias »void (*)(int,  int)«} erwartet, aber Argument hat Typ »gboolean (*)(int,  int)« {alias »int (*)(int,  int)«}
   81 | void cairo_dock_change_nb_viewports (int iDeltaNbDesktops, GldiChangeViewportFunc cb);
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~^~
/var/tmp/pamac-build-raphael/cairo-dock-core-wayland-git/src/cairo-dock-core-wayland-git/src/implementations/cairo-dock-compiz-integration.c: In Funktion »_remove_workspace«:
/var/tmp/pamac-build-raphael/cairo-dock-core-wayland-git/src/cairo-dock-core-wayland-git/src/implementations/cairo-dock-compiz-integration.c:347:45: Fehler: Übergabe des Arguments 2 von »cairo_dock_change_nb_viewports« von inkompatiblem Zeigertyp [-Wincompatible-pointer-types]
  347 |         cairo_dock_change_nb_viewports (-1, _compiz_set_nb_viewports);
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             gboolean (*)(int,  int) {alias int (*)(int,  int)}
/var/tmp/pamac-build-raphael/cairo-dock-core-wayland-git/src/cairo-dock-core-wayland-git/src/implementations/cairo-dock-X-utilities.h:81:83: Anmerkung: »GldiChangeViewportFunc« {alias »void (*)(int,  int)«} erwartet, aber Argument hat Typ »gboolean (*)(int,  int)« {alias »int (*)(int,  int)«}
   81 | void cairo_dock_change_nb_viewports (int iDeltaNbDesktops, GldiChangeViewportFunc cb);
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~^~`
      
```
     OS: Manjaro Linux x86_64
Host: MS-7B89 (1.0)
Kernel: Linux 6.11.2-4-MANJARO
Uptime: 4 hours, 44 mins
Packages: 2283 (pacman)[stable], 10 (snap)
Shell: bash 5.2.37
Display (27GL850): 2560x1440 @ 144 Hz in 27″ [External]
DE: KDE Plasma 6.1.5
WM: KWin (Wayland)
WM Theme: Breeze
Theme: Breeze (MateriaManjaroDark) [Qt], Breath-Dark [GTK2/3/4]
Icons: Materia-Manjaro-Breeze-Dark [Qt], Materia-Manjaro-Breeze-Dark [GTK2/3/4]
Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
Cursor: breeze (24px)
Terminal: konsole 24.8.1
Terminal Font: Hack (10pt)
 
```

using
https://aur.archlinux.org/packages/cairo-dock-core-wayland-git

**Comment by dkondor** [comment]
Hi,
thanks for reporting! Does using the following branch help?
https://github.com/dkondor/cairo-dock-core/tree/fix_53

**Comment by Raphisu** [comment]
I tried, but unfortunately I can't find the correct way to patch the PKGBUILD file to use the new branch.
For instance I tried:
```
source=(
    "${pkgname}::git+https://github.com/Cairo-Dock/cairo-dock-core.git#branch=fix_53"
```

Sorry for my obvious incompetence in this matter ;)

**Comment by dkondor** [comment]
No worries! I merged the fix, so you can just try building normally without adjustments, and let me know if it is still not working

**Comment by Raphisu** [comment]
Nice. I resetted the PKGBUILD and it compiles now. 
I verified that I have the newest "cairo-dock-compiz-integration.c" on the disk, so it seems to be fine now. 
Thanks for taking care so swiftly :+1:
