### ISSUE TITLE
Cannot drop in Firefox launcher

### ISSUE THREAD

**Issue by HighValueWarrior** [Cairo-Dock/cairo-dock-core#57]
Fresh install latest version, new configs,
Can drag firefox launcher to dock fine, but it will not accept.
Able to drag other launchers with no issues.

Arch linux, KDE, running in X11 (wayland/mesa currently broken)

**Comment by dkondor** [comment]
Thanks for reporting! Do you mean that dragging an URL onto the Firefox icon does not work? I can reproduce this and have a fix here: https://github.com/Cairo-Dock/cairo-dock-core/pull/58
Let me know if this solves the issue

**Comment by HighValueWarrior** [comment]
Dragging the app from apps list on to dock does not work - but it seems only the Firefox app is affected.

**Comment by dkondor** [comment]
Thanks for the update, I see (I originally thought the issue is with dropping links onto the Firefox launcher once it's added). Unfortunately, I cannot reproduce this so far. Some questions for clarification:
 - Are you dragging the app from Cairo-Dock's menu? (Applications Menu plugin)
 - How did you install Firefox? Is it from the package manager or Snap or other source?
 - What happens if you try to drag the app icon into a text editor? (e.g. gedit or kate) Does it open the desktop file showing info about Firefox? If yes, what is the path of the opened file?

I'll also think of additional tests to diagnose the issue better.

**Comment by HighValueWarrior** [comment]
Are you dragging the app from Cairo-Dock's menu? (Applications Menu plugin)
Yes. Tried from app menu and also from start menu.
    How did you install Firefox? Is it from the package manager or Snap or other source?
All pkgs, from arch repos.
    What happens if you try to drag the app icon into a text editor? (e.g. gedit or kate) Does it open the desktop file showing info about Firefox? If yes, what is the path of the opened file?
Yes, see below.

[Desktop Action new-private-window]
Exec=/usr/lib/firefox/firefox --private-window %u
Name[en_US]=New Private Window
Name=Open a New Private Window

[Desktop Action new-window]
Exec=/usr/lib/firefox/firefox --new-window %u
Name[en_US]=New Window
Name=Open a New Window

[Desktop Action profile-manager-window]
Exec=/usr/lib/firefox/firefox --ProfileManager
Name=Open the Profile Manager

[Desktop Entry]
Actions=new-window;new-private-window;profile-manager-window;
Categories=Network;WebBrowser;
Comment=Browse the World Wide Web
Exec=/usr/lib/firefox/firefox %u
GenericName=Web Browser
Icon=firefox
Keywords=Internet;WWW;Browser;Web;Explorer
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;application/pdf;application/json;
Name=Firefox Web Browser
NoDisplay=false
Path=
StartupNotify=true
StartupWMClass=firefox
Terminal=false
TerminalOptions=
Type=Application
Version=1.0
X-KDE-SubstituteUID=false
X-KDE-Username=

I have 3 systems. 2 desktops with amd gpus and one laptop with intel/nvidia hybrid graphics. On laptop with primary intel gpu I am able to drag Firefox to dock. Have uninstalled completely including config files and reinstalled several times. Dock seems to work perfectly aside from this one specific issue. Frustrating to say the least.

**Comment by dkondor** [comment]
This is very weird, your .desktop file seems to be in the wrong format -- it should start with the `[Desktop Entry]˙ section (see e.g. [here](https://specifications.freedesktop.org/desktop-entry-spec/latest/basic-format.html)). Also it does not match what's in the [Arch repo](https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/main/firefox.desktop?ref_type=heads). With this version, Cairo-Dock should work. So maybe the nonstandard file you have is left over from a previous install of Firefox? The only other possibly relevant change is the ` X-KDE-SubstituteUID=false` key that I have not idea what it does (and cannot find any info about).

What you can do is:
 - see if you have `/usr/share/applications/firefox.desktop` and if yes, does it contain the text you pasted or the correct version? If the former, replacing this with the [version](https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/main/firefox.desktop?ref_type=heads) from the package should work.
 - If it is correct, you probably have the "wrong" version in `/usr/local/share/applications` or `~/.local/share/applications` or some other path in your `$XDG_DATA_DIRS` paths (if you drag from the menu to the file editor it should also show the path). Deleting that file should fix the problem.

For Cairo-Dock I'll consider adding a better error reporting mechanism to report errors if it cannot parse the app's .desktop file when trying to add a launcher.

**Comment by HighValueWarrior** [comment]
Weird indeed. I will try a saving my Firefox config and then uninstall reinstall as well as to see if fresh will work.

What you can do is:

    see if you have /usr/share/applications/firefox.desktop and if yes, does it contain the text you pasted or the correct version? If the former, replacing this with the [version](https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/main/firefox.desktop?ref_type=heads) from the package should work.

** just checked and does not match with file I tried to drag - so strange.  I update every day and pride myself on a 'clean' system.

Thanks for your quick responses to these issues. We owe you a lot for maintaining the only wayland dock .

Thank you Daniel.

**Comment by dkondor** [comment]
My feeling is that you probably have the "bad" launcher in `~/.local/share/applications`, but could be another weird location. If you drag it into a text editor, it should say where the file is opened from.

**Comment by HighValueWarrior** [comment]
Daniel,
I thought I had posted earlier, but it does not seem to have published.
Yes it was indeed a bad  launcher, I had to manually uninstall and find all old entries.
A fresh install then worked perfectly.

Very glad to hear you have implemented a launcerh parse.
Keep up the great work.

**Comment by dkondor** [comment]
OK, great to hear it's resolved!
