### ISSUE TITLE
cpuwatcher not working with cairo-dock core / plug-ins 3.5.99.beta6 (okay with beta5)

### ISSUE THREAD

**Issue by mtasaka** [Cairo-Dock/cairo-dock-core#66]
Looks like extras CpuWatcher 
https://github.com/Cairo-Dock/cairo-dock-plug-ins-extras/blob/master/CpuWatcher/CpuWatcher

stopped working with cairo-dock
* core 3.5.99.beta6 https://github.com/Cairo-Dock/cairo-dock-core/commit/4f36d13797c2ca508376c15d462cf644e71f69fb
* plug-ins 3.5.99.beta6 https://github.com/Cairo-Dock/cairo-dock-plug-ins/commit/ce0764fcfca710cdb3c439f963aa4474523cc110

CpuWatcher shows icon, but does not show actual CPU usage info.

With 
* core 3.5.99.beta5 https://github.com/Cairo-Dock/cairo-dock-core/commit/ea4bd9735da0e6fa199c9b99e58b76e296c6448c
* plug-ins 3.5.99.beta5 https://github.com/Cairo-Dock/cairo-dock-plug-ins/commit/ce518e9ed0f8a54be850e0a8fe55e274885b014e

CpuWatcher was working (I've confirmed)

Currently I don't know where to debug from.

**Comment by dkondor** [comment]
Hi,
thank you for reporting! I think I have a solution, see https://github.com/Cairo-Dock/cairo-dock-plug-ins/pull/30
Could you test if it fixes your issue? (you only need to update the plug-ins, using the [branch](https://github.com/dkondor/cairo-dock-plug-ins/tree/fix_dbus_launch) from the PR, not core)

**Comment by mtasaka** [comment]
Yes, I've confirmed that https://github.com/Cairo-Dock/cairo-dock-plug-ins/pull/30 makes CpuWatcher working again, thank you!
